BANKS = {
    # ===== BANK NASIONAL =====
    "bca": {"name": "BCA", "code": "bank_bca"},
    "bca_syariah": {"name": "BCA SYARIAH", "code": "bank_bca_syr"},
    "bri": {"name": "BRI", "code": "bank_bri"},
    "bni": {"name": "BNI", "code": "bank_bni"},
    "mandiri": {"name": "MANDIRI", "code": "bank_mandiri"},
    "btn": {"name": "BTN", "code": "bank_btn"},
    "btn_syariah": {"name": "BTN SYARIAH", "code": "bank_btn_syr"},
    "bsi": {"name": "BSI (BANK SYARIAH INDONESIA)", "code": "bank_bsm"},
    "cimb": {"name": "CIMB NIAGA", "code": "bank_cimb"},
    "danamon": {"name": "DANAMON", "code": "bank_danamon"},
    "danamon_syariah": {"name": "DANAMON SYARIAH", "code": "bank_danamon_syr"},
    "permata": {"name": "PERMATA", "code": "bank_permata"},
    "permata_syariah": {"name": "PERMATA SYARIAH", "code": "bank_permata_syr"},
    "panin": {"name": "PANIN BANK", "code": "bank_panin"},
    "panin_syariah": {"name": "PANIN DUBAI SYARIAH", "code": "bank_panin_syr"},
    "ocbc": {"name": "OCBC NISP", "code": "bank_ocbc"},
    "ocbc_syariah": {"name": "OCBC NISP SYARIAH", "code": "bank_ocbc_syr"},
    "hsbc": {"name": "HSBC INDONESIA", "code": "bank_hsbc"},
    "citibank": {"name": "CITIBANK", "code": "bank_citibank"},
    "standard_chartered": {"name": "STANDARD CHARTERED BANK", "code": "bank_standard_chartered"},
    "uob": {"name": "UOB / TMRW", "code": "bank_uob"},
    "maybank": {"name": "MAYBANK INDONESIA", "code": "bank_bii"},
    "maybank_syariah": {"name": "MAYBANK SYARIAH", "code": "bank_bii_syr"},
    "dbs": {"name": "DBS INDONESIA", "code": "bank_dbs"},
    "bnp": {"name": "BNP PARIBAS INDONESIA", "code": "bank_bnp_paribas"},
    "mizuho": {"name": "MIZUHO INDONESIA", "code": "bank_mizuho"},
    "deutsche": {"name": "DEUTSCHE BANK", "code": "bank_deutsche"},
    "boc": {"name": "BANK OF CHINA", "code": "bank_boc"},
    "anz": {"name": "ANZ INDONESIA", "code": "bank_anz"},
    "woori": {"name": "WOORI SAUDARA", "code": "bank_woori"},
    "shinhan": {"name": "SHINHAN INDONESIA", "code": "bank_shinhan"},
    "resona": {"name": "RESONA PERDANIA", "code": "bank_resona_perdania"},
    "qnb": {"name": "QNB INDONESIA", "code": "bank_qnb_kesawan"},
    "rabobank": {"name": "RABOBANK", "code": "bank_rabobank"},
    "jpmorgan": {"name": "JPMORGAN CHASE", "code": "bank_jpmorgan_chase"},
    "boa": {"name": "BANK OF AMERICA", "code": "bank_america_na"},

    # ===== BANK DIGITAL =====
    "jago": {"name": "BANK JAGO", "code": "bank_artos"},
    "blu": {"name": "BLU (BCA DIGITAL)", "code": "bank_royal"},
    "neo": {"name": "BANK NEO COMMERCE", "code": "bank_yudha_bakti"},
    "linebank": {"name": "LINE BANK", "code": "bank_hana"},
    "seabank": {"name": "SEABANK", "code": "bank_kesejahteraan_ekonomi"},
    "superbank": {"name": "SUPERBANK", "code": "bank_super"},
    "krom": {"name": "KROM BANK", "code": "bank_krom"},
    "saqu": {"name": "BANK SAQU", "code": "bank_saqu"},

    # ===== BANK DAERAH =====
    "dki": {"name": "BANK DKI", "code": "bank_dki"},
    "dki_syariah": {"name": "BANK DKI SYARIAH", "code": "bank_dki_syr"},
    "bjb": {"name": "BJB", "code": "bank_bjb"},
    "bjb_syariah": {"name": "BJB SYARIAH", "code": "bank_bjb_syr"},
    "jateng": {"name": "BANK JATENG", "code": "bank_jawa_tengah"},
    "jateng_syariah": {"name": "BANK JATENG SYARIAH", "code": "bank_jawa_tengah_syr"},
    "jatim": {"name": "BANK JATIM", "code": "bank_jawa_timur"},
    "jatim_syariah": {"name": "BANK JATIM SYARIAH", "code": "bank_jawa_timur_syr"},
    "kalbar": {"name": "BANK KALBAR", "code": "bank_kalimantan_barat"},
    "kalsel": {"name": "BANK KALSEL", "code": "bank_kalimantan_selatan"},
    "kaltim": {"name": "BANK KALTIMTARA", "code": "bank_kalimantan_timur"},
    "lampung": {"name": "BANK LAMPUNG", "code": "bank_lampung"},
    "sumut": {"name": "BANK SUMUT", "code": "bank_sumut"},
    "sumut_syariah": {"name": "BANK SUMUT SYARIAH", "code": "bank_sumut_syr"},
    "sumbar": {"name": "BANK NAGARI", "code": "bank_sumatera_barat"},
    "sumsel": {"name": "BANK SUMSEL BABEL", "code": "bank_sumsel_dan_babel"},
    "bali": {"name": "BPD BALI", "code": "bank_bali"},
    "papua": {"name": "BANK PAPUA", "code": "bank_papua"},
}
